- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy artifact.tar.gz file
  template:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Uncompress Backend
  shell: |
    cd /home/ubuntu/backend
    tar xvzf artifact.tar.gz -C .
    ls -la

- name: Build
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm run build

- name: Start PM2
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
