- name: "update apt packages."
  apt:
    update_cache: yes

- name: "upgrade packages"
  apt:
    upgrade: yes

#- name: remove dependencies that are no longer required
 # apt:
  #  autoremove: yes

- name: install node
  shell: |
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs

- name: "Install zip utility."
  apt:
    name: [ "zip", "unzip" ]
    state: latest
    update_cache: yes

- name: "install pm2"
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Creates backend app directory"
  file:
    path: /home/ubuntu/backend_app_dir
    state: directory
    
- name: "send build artifact to ec2 app"
  unarchive:
    src: "artifact.tar.gz"
    dest: "/home/ubuntu/backend_app_dir/"

- name: "install artifact"
  npm: 
    path: /home/ubuntu/backend_app_dir/
    global: true
    production: true
  
  
  
- name: "Executing node"
  shell: |
    cd /home/ubuntu/backend_app_dir/
    pm2 stop all 
    pm2 start npm -- run -- start
   # pm2 start /home/ubuntu/backend_app_dir/main.js -f
 # register: execute_node
 
 

#- name: "Unzip backend files to correct directory"
 # shell: |
  #  cd /home/ubuntu/backend_app_dir/
   # unzip dist.zip
    #rm -rf dist.zip


#- name: "Install dependencies for project"
 # shell: |
  #  cd /home/ubuntu/backend_app_dir
   # npm install -g npm@latest
    #npm install
    #npm run build
    
  
#- name: "Executing node"
 # shell: |
  #  npm i -g pm2
   # pm2 start /home/ubuntu/backend_app_dir/main.js -f
  #register: execute_node
  
  
#- name: print message
 # debug:
  #  msg: "{{ execute_node.stdout_lines }}"

