- name: "Creates backend app directory"
  file:
    path: ~/backend_app_dir
    state: directory

- name: "Copy compiled backend app"
  copy:
    src: files/dist.zip
    dest: "~/backend_app_dir/dist.zip"

- name: "Unzip backend files to correct directory"
  shell: |
    cd ~/backend_app_dir
    unzip dist.zip
    rm -rf dist.zip

- name: "Install dependencies for project"
  shell: |
    cd ~/backend_app_dir
    npm install
    
- name: Install PM2
  npm:
    name: pm2
    global: yes
    
- name: "Executing node"
  shell: |
    npm i -g pm2
    pm2 start ~/backend_app_dir/dist/main.js -f
  register: execute_node
  
  
- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu
