#- name: "update apt packages."
 # apt:
  #  update_cache: yes

#- name: "upgrade packages"
 # apt:
  #  upgrade: yes

#- name: remove dependencies that are no longer required
 # apt:
  #  autoremove: yes

#- name: install node
 # shell: |
  #  curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs

#- name: "Install zip utility."
 # apt:
  #  name: [ "zip", "unzip" ]
   # state: latest
    #update_cache: yes

#- name: "install python3."
 # become: true
  #apt:
   # name: ["python3"]
    #state: latest
    #update_cache: true
    
#- name: "update apt packages."
 # apt:
  #  update_cache: yes    

#- name: "upgrade packages"
 # become: true
  #apt:
   # upgrade: true

#- name: remove dependencies that are no longer required
 # become: true
  #apt:
   # autoremove: true

#- name: "install dependencies."
 # become: true
  #apt:
   # name: ["nodejs", "npm"]
    #state: latest

#- name: "install n (node version manager)"
 # become: true
  #npm:
   # name: n
    #global: true
    #production: true

#- name: "switch to node v13.8.0"
 # become: true
  #shell: n 13.8.0
  
#- name: "install pm2"
 # become: true
  #npm:
   # name: pm2
    #global: true
    #production: true
    #state: present

- name: "create project dir"
  shell: mkdir ~/backend2

- name: "send build atrifacts to remote"
  unarchive:
    src: ../../artifact.tar.gz
    dest: ~/backend2

- name: "install backend artifacts"
  npm:
    path: ~/backend2
    production: true
    global: true
    
- name: "Install dependencies for project"
  shell: |
    cd ~/backend2
    npm install
    

- name: "start the app"
  shell: cd ~/backend2 && pm2 stop all; pm2 start npm -- run start

 
 
 # pm2 start /home/ubuntu/backend_app_dir/main.js -f
 # register: execute_node
 
 

#- name: "Unzip backend files to correct directory"
 # shell: |
  #  cd /home/ubuntu/backend_app_dir/
   # unzip dist.zip
    #rm -rf dist.zip


#- name: "Install dependencies for project"
 # shell: |
  #  cd /home/ubuntu/backend_app_dir
   # npm install -g npm@latest
    #npm install
    #npm run build
    
  
#- name: "Executing node"
 # shell: |
  #  npm i -g pm2
   # pm2 start /home/ubuntu/backend_app_dir/main.js -f
  #register: execute_node
  
  
#- name: print message
 # debug:
  #  msg: "{{ execute_node.stdout_lines }}"

